# Default values for k8s-webhook-autoscaler-logger.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: julienstroheker/kubernetes-webhook-autoscaler-logger
  tag: latest
  pullPolicy: Always
service:
  name: k8s-wh-as-logger
  type: ClusterIP
  externalPort: 5000
  internalPort: 5000
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
