{{- if and .Values.options.scaleoutwebhook .Values.options.scaleinwebhook .Values.options.poolnameregex -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
{{ include "labels.standard" . | indent 8 }}
        openai/do-not-drain: "true"
    spec:
{{- if .Values.rbac.install }}
      serviceAccountName: webhook-autoscaler
{{- end }}
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command:
            - python
            - main.py
            - --scale-out-webhook
            - {{ .Values.options.scaleoutwebhook }}
            - --scale-in-webhook
            - {{ .Values.options.scaleinwebhook }}
            - --pool-name-regex
            - {{ .Values.options.poolnameregex }}
            {{- if .Values.options.drain }}
            - --drain
            - {{ .Values.options.drain }}
            {{- end }}
            {{- if .Values.options.sleeptime }}
            - --sleep
            - {{ .Values.options.sleeptime | quote }}
            {{- end }}
            {{- if .Values.options.ignorepools }}
            - --ignore-pools 
            - {{ .Values.options.ignorepools }}
            {{- end }}
            {{- if .Values.options.spareagents }}
            - --spare-agents 
            - {{ .Values.options.spareagents | quote }}
            {{- end }}
            {{- if .Values.options.idlethreshold }}
            - --idle-threshold 
            - {{ .Values.options.idlethreshold | quote }}
            {{- end }}
            {{- if .Values.options.overprovision }}
            - --over-provision 
            - {{ .Values.options.overprovision | quote }}
            {{- end }}
            - -vvv
            - --debug
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      restartPolicy: Always
{{- end }}